name: Backend Unit Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies and run tests
        run: |
          echo "Creating virtual environment..."
          python -m venv venv

          echo "Activating virtual environment..."
          source venv/bin/activate

          echo "Installing Python dependencies..."
          pip install -r requirements.txt

          echo "Installing pytest..."
          pip install pytest httpx

          echo "Starting Uvicorn server in background..."
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          UVICORN_PID=$!

          echo "Waiting for Uvicorn to start (5 seconds)..."
          sleep 5

          echo "Running backend tests..."
          # Add PYTHONPATH so 'app' package is importable
          PYTHONPATH=$PWD pytest unit-tests/ -v -W ignore::pydantic.PydanticDeprecatedSince20

          echo "Stopping Uvicorn server..."
          kill $UVICORN_PID
        shell: bash

