name: Backend CI

on:
  push:
    branches: [backend, backend-unit-testing]
  pull_request:
    branches: [backend, backend-unit-testing]

jobs:
  backend-checks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      # Step 4: Run linting (relaxed)
      - name: Run flake8 linter (ignore all rules for now)
        run: |
          echo "[flake8]" > .flake8
          echo "max-line-length = 120" >> .flake8
          echo "ignore = E,W,F,C" >> .flake8
          echo "exclude = venv,.git,__pycache__,migrations" >> .flake8
          flake8 .

      # Step 5: Run tests
      - name: Run unit tests with pytest
        run: |
          pytest tests/ --maxfail=5 --disable-warnings -v
