name: Run Frontend Tests Before Merge

on:
  pull_request:
    branches:
      - main

jobs:
  frontend_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Checks out your repository code into the runner's environment.
        # This is essential for the workflow to access your project files.
        uses: actions/checkout@v4

      - name: Set up Node.js
        # Sets up the Node.js environment required for npm commands.
        # '20.x' is a common stable version, you can adjust this if needed.
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm' # Caches npm dependencies to speed up subsequent runs

      - name: Change to frontend directory
        # Navigates into the 'frontend' directory where your package.json is located.
        # This is crucial for 'npm install' and 'npm run test:run' to work correctly.
        run: cd ./frontend

      - name: Install frontend dependencies
        # Installs all the necessary npm packages defined in frontend/package.json.
        # The 'cd frontend' from the previous step ensures this runs in the correct directory.
        run: npm ci

      - name: Run frontend tests
        # Executes your test script.
        # This command is run from within the 'frontend' directory due to the 'cd' step.
        run: npm run test:run