name: Frontend Unit Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  frontend_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Checks out your repository code into the runner's environment.
        # This is essential for the workflow to access your project files.
        uses: actions/checkout@v3

      - name: Set up Node.js
        # Sets up the Node.js environment required for npm commands.
        # '20.x' is a common stable version, you can adjust this if needed.
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm' # Caches npm dependencies to speed up subsequent runs

      - name: Install and Test Frontend
        run: |
            cd frontend
            npm ci
            npm run test:run