name: Backend Integration Tests

on:
  push:
    branches:
      - main
      - dev
      - 252-finalised-testing
  pull_request:
    branches:
      - main
      - dev
      - 252-finalised-testing

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Create .env file
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db" >> .env
          echo "SUPABASE_URL=your_supabase_url" >> .env
          echo "SUPABASE_ANON_KEY=your_supabase_anon_key" >> .env

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest httpx psycopg2-binary alembic python-dotenv

      - name: Run Alembic migrations
        run: |
          source venv/bin/activate
          alembic upgrade head

      - name: Start Uvicorn server
        run: |
          source venv/bin/activate
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          echo $! > uvicorn_pid.txt
          sleep 10

      - name: Run integration tests
        run: |
          source venv/bin/activate
          pytest integration-tests/ -v -p no:warnings --tb=short

      - name: Stop Uvicorn server
        run: |
          kill $(cat uvicorn_pid.txt) || echo "Server already stopped"
