name: Backend Integration Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend_integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Create .env file
        run: |
          echo "DATABASE_URL=postgresql://postgres.httrffbdyhzwfocrwxhr:X4wcx62kVzC0V0u6@aws-0-eu-central-1.pooler.supabase.com:5432/postgres" >> .env

      - name: Install dependencies and run tests
        run: |
          echo "Creating virtual environment..."
          python -m venv venv

          echo "Activating virtual environment..."
          source venv/bin/activate

          echo "Installing Python dependencies..."
          pip install -r requirements.txt

          echo "Installing pytest..."
          pip install pytest httpx

          echo "Starting Uvicorn server in background..."
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          UVICORN_PID=$!

          echo "Waiting for Uvicorn to start..."
          for i in {1..10}; do
            if curl -s http://localhost:8000/docs > /dev/null; then
              echo "Uvicorn is up!"
              break
            fi
            echo "Still waiting for Uvicorn..."
            sleep 2
          done

          echo "Running integration tests..."
          PYTHONPATH=$PWD pytest integration-tests/ -v -p no:warnings

          echo "Stopping Uvicorn server..."
          kill $UVICORN_PID
        shell: bash
