name: Integration Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Create .env file
        run: |
          echo "DATABASE_URL=postgresql://postgres.httrffbdyhzwfocrwxhr:X4wcx62kVzC0V0u6@aws-0-eu-central-1.pooler.supabase.com:5432/postgres" >> .env

      - name: Install dependencies and run tests
        run: |
          echo "Creating virtual environment..."
          python -m venv venv

          echo "Activating virtual environment..."
          # Activate the virtual environment. Note: 'source' is for bash/zsh,
          # for GitHub Actions, it's generally safe to use directly.
          source venv/bin/activate

          echo "Installing Python dependencies..."
          pip install -r requirements.txt

          echo "Installing pytest..."
          pip install pytest httpx

          echo "Starting Uvicorn server in background..."
          # Start Uvicorn. We use 'nohup' and '&' to run it in the background
          # and capture its process ID (PID).
          # '--host 0.0.0.0' makes it accessible within the container.
          # We remove '--reload' as it's typically not needed in CI and can cause issues.
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          UVICORN_PID=$! # Store the PID of the Uvicorn process

          echo "Waiting for Uvicorn to start (5 seconds)..."
          # Give Uvicorn a moment to fully initialize.
          # For more robust checks, you could use 'curl' to hit a health endpoint.
          sleep 5

          echo "Running backend tests..."
          # Execute your pytest commands.
          # The virtual environment is active, so pytest will use installed packages.
          python -m pytest integration-tests/ -v -p no:warnings

          echo "Stopping Uvicorn server..."
          # Kill the Uvicorn process using its stored PID.
          kill $UVICORN_PID

        shell: bash