name: Backend Integration Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend_integration_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: greencart
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Create .env file
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/greencart" >> .env

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Start Uvicorn server in background
        run: |
          source venv/bin/activate
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          UVICORN_PID=$!
          echo $UVICORN_PID > uvicorn.pid

          echo "Waiting for Uvicorn to be ready..."
          for i in {1..10}; do
            if curl -s http://localhost:8000/docs > /dev/null; then
              echo "Uvicorn is up!"
              break
            fi
            echo "Retrying in 2s..."
            sleep 2
          done

      - name: Run integration tests
        run: |
          source venv/bin/activate
          PYTHONPATH=$PWD pytest integration-tests/ -v -p no:warnings

      - name: Stop Uvicorn server
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then
            kill $(cat uvicorn.pid)
          fi
