# .github/workflows/lint.yml

name: Code Linting

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Run Flake8 linting
        run: flake8 .
        working-directory: ./app

  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
        working-directory: ./frontend

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run ESLint linting
        run: npm run lint
        working-directory: ./frontend
